services:
  besu:
    image: hyperledger/besu:25.9.0
    command: >
      --network=dev
      --miner-enabled=true
      --miner-coinbase=0x0000000000000000000000000000000000000000
      --host-allowlist="*"
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-api=ETH,NET,WEB3,TXPOOL,TRACE,DEBUG
      --rpc-ws-enabled
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=8546
    ports:
      - "8545:8545"
      - "8546:8546"
    restart: unless-stopped
